package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"YALS/internal/agent"
	"YALS/internal/config"
	"YALS/internal/logger"
	"YALS/internal/plugin"
	"YALS/internal/utils"

	_ "YALS/internal/plugin/agent"
)

func main() {
	serverHost := flag.String("s", "", "Server host or address")
	serverPort := flag.Int("p", 443, "Server port")
	agentUUID := flag.String("u", "", "Agent UUID generated by server")
	agentToken := flag.String("t", "", "Agent token issued by server")
	showVersion := flag.Bool("version", false, "Show version information")
	flag.Parse()

	if *showVersion {
		plugins := plugin.GetRegisteredPlugins()
		fmt.Printf("%s Agent\n%s\n", utils.GetAppName(), utils.GetVersionInfo(plugins))
		os.Exit(0)
	}

	if *serverHost == "" || *serverPort <= 0 || *agentUUID == "" || *agentToken == "" {
		logger.Fatalf("Usage: yals_agent -s <server> -p <port> -u <uuid> -t <token>")
	}

	logger.SetGlobalLevelFromString("info")

	logger.Infof("Starting YALS Agent bootstrap")
	logger.Infof("Server: %s:%d", *serverHost, *serverPort)
	logger.Infof("UUID: %s", *agentUUID)

	agentConfig := &config.AgentConfig{}
	agentConfig.Server.Host = *serverHost
	agentConfig.Server.Port = *serverPort
	agentConfig.Server.UUID = *agentUUID
	agentConfig.Server.Token = *agentToken
	agentConfig.Log.LogLevel = "info"

	agentClient := agent.NewClientWithConfig(agentConfig)

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)

	go func() {
		for {
			err := agentClient.ConnectToServer()
			if err != nil {
				logger.Errorf("Connection failed: %v", err)
				logger.Info("Retrying in 10 seconds...")
				time.Sleep(10 * time.Second)
				continue
			}
			logger.Info("Connection closed, retrying in 5 seconds...")
			time.Sleep(5 * time.Second)
		}
	}()

	<-stop
	logger.Info("Shutting down agent...")
}
